name: Auto create a PR

permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      base:
        description: "The base branch"
        required: true
        type: string
      head:
        description: "The head branch"
        required: true
        type: string

jobs:
  auto-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create PR between two branches
        run: |
          COUNT=$(gh pr list \
            --head ${{ inputs.head }} \
            --base ${{ inputs.base }} \
            --state open \
            --json number \
            --jq 'length')
          
          if [ "$COUNT" -eq 0 ]; then
            gh pr create \
              --head ${{ inputs.head }} \
              --base ${{ inputs.base }} \
              --title "Sync ${{ inputs.head }} to ${{ inputs.base }}" \
              --body "Automated PR to sync ${{ inputs.head }} into ${{ inputs.base }}"

          else
            echo "PR already exists. Skipping creation."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}